[remote]
enabled = false
host = 161.189.17.221
port = 33129
username = shentou2
password = Digital1wdv!

[local]
host = 127.0.0.1
port = 7463
max_connections = 200

[socks5_auth]
enabled = false
username = local_user
password = local_pass

[relay]
timeout = 60
buffer_size = 4096

